### ISSUE TITLE
app fails when you make many notes

### ISSUE THREAD

**Issue by c78945** [szafir1100/notepad#23]
Especially if i'm using bitmap it easily exceeds gc heap and gives

errors example=
/OpenGLRenderer: endAllStagingAnimators on 0xdcb7fb00 (RippleDrawable) with handle 0xe10a3f90
I/art: Background sticky concurrent mark sweep GC freed 128(13KB) AllocSpace objects, 3(53KB) LOS objects, 0% free, 227MB/227MB, paused 7.058ms total 8.749ms
I/art: Clamp target GC heap from 256MB to 256MB
I/art: Clamp target GC heap from 268MB to 256MB
I/art: Alloc partial concurrent mark sweep GC freed 10(320B) AllocSpace objects, 1(18KB) LOS objects, 1% free, 252MB/256MB, paused 397us total 5.502ms
I/art: Clamp target GC heap from 268MB to 256MB
I/art: Alloc concurrent mark sweep GC freed 6(12KB) AllocSpace objects, 0(0B) LOS objects, 1% free, 252MB/256MB, paused 290us total 6.921ms
I/art: Forcing collection of SoftReferences for 12MB allocation
I/art: Clamp target GC heap from 268MB to 256MB
I/art: Alloc concurrent mark sweep GC freed 11(344B) AllocSpace objects, 0(0B) LOS objects, 1% free, 252MB/256MB, paused 397us total 7.504ms
E/art: Throwing OutOfMemoryError "Failed to allocate a 12879372 byte allocation with 3871833 free bytes and 3MB until OOM"
D/skia: --- decoder->decode returned false
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.briswell.mycalendar, PID: 8384
                  java.lang.OutOfMemoryError: Failed to allocate a 12879372 byte allocation with 3871833 free bytes and 3MB until OOM
                      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                      at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
                      at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:522)
                      at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:545)
                      at com.briswell.mycalendar.diary.BitmapConverter.getImage(BitmapConverter.java:23)
                      at com.briswell.mycalendar.diary.DatabaseHandler.getAllNotesAsArrayList(DatabaseHandler.java:213)
                      at com.briswell.mycalendar.diary.SaveOrUpdateNoteTask.updateNoteListView(SaveOrUpdateNoteTask.java:65)
                      at com.briswell.mycalendar.diary.SaveOrUpdateNoteTask.onPostExecute(SaveOrUpdateNoteTask.java:59)
                      at com.briswell.mycalendar.diary.SaveOrUpdateNoteTask.onPostExecute(SaveOrUpdateNoteTask.java:13)
                      at android.os.AsyncTask.finish(AsyncTask.java:632)
                      at android.os.AsyncTask.access$600(AsyncTask.java:177)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

how can i get rid of this OutOfMemory error?

**Comment by c78945** [comment]
if the notes have drawing a little bit, it couldn't take 3 or more notes,
if the notes don't have drawings and just letters, i was able to make lots of notes. I think if i make notes then all the notes that i have directly take memory. 
I tried to solve this problem, but my programming skill is bad, I still couldn't figure how to solve this problem. I really thank you if you can solve this problem. 
Thank you for reading this comment.

**Comment by tmarzeion** [comment]
@c78945 
NVM, I see HUGE memory leaks in this app. Ill fix them today

**Comment by c78945** [comment]
Thank you, if I was able to fix this, I fixed it and let you know but I couldn't.. I'm learning from your app a lot.

**Comment by tmarzeion** [comment]
@c78945 
Ill check it out, how many notes did u have?

**Comment by tmarzeion** [comment]
Fixed at https://github.com/tmarzeion/drawable-notepad/commit/2a9380f6d5813abad8ac7551e002d90aa79296fe
Sorry for that issue, a lot of people was complaining about it :/
I hope that this app will rise from dead, since there were about 150 downloads/day and now there are about 30

**Comment by tmarzeion** [comment]
@c78945 
Thanks for reporting it :)

**Comment by tmarzeion** [comment]
https://github.com/tmarzeion/drawable-notepad/commit/2a9380f6d5813abad8ac7551e002d90aa79296fe

**Comment by c78945** [comment]
wow.. fixed so quickly. Thank you, I'll go study how to fix this problem.

**Comment by c78945** [comment]
It's weird that i'm having same problem.. so sad..
Everytime I use drawing a little bit, this error appears

"Clamp target gc heap xxMB to 96MB" 
sorry for bothering
===============================================================
11-06 05:22:16.393 5826-5845/com.tomaszmarzeion.notepad D/OpenGLRenderer: endAllStagingAnimators on 0xe2cdd580 (RippleDrawable) with handle 0xe28ff9b0
11-06 05:22:16.449 5826-5826/com.tomaszmarzeion.notepad I/art: Alloc partial concurrent mark sweep GC freed 5677(308KB) AllocSpace objects, 19(13MB) LOS objects, 17% free, 77MB/93MB, paused 215us total 5.039ms
11-06 05:22:16.483 5826-5826/com.tomaszmarzeion.notepad I/art: Clamp target GC heap from 106MB to 96MB
11-06 05:22:16.490 5826-5826/com.tomaszmarzeion.notepad I/art: Alloc concurrent mark sweep GC freed 4258(273KB) AllocSpace objects, 18(12MB) LOS objects, 17% free, 76MB/92MB, paused 320us total 7.043ms
11-06 05:22:16.523 5826-5826/com.tomaszmarzeion.notepad I/art: Clamp target GC heap from 105MB to 96MB
11-06 05:22:16.529 5826-5826/com.tomaszmarzeion.notepad I/art: Clamp target GC heap from 105MB to 96MB
11-06 05:22:16.529 5826-5826/com.tomaszmarzeion.notepad I/art: Alloc concurrent mark sweep GC freed 5(128B) AllocSpace objects, 0(0B) LOS objects, 7% free, 89MB/96MB, paused 196us total 5.380ms
11-06 05:22:16.529 5826-5826/com.tomaszmarzeion.notepad I/art: Forcing collection of SoftReferences for 12MB allocation
11-06 05:22:16.535 5826-5826/com.tomaszmarzeion.notepad I/art: Clamp target GC heap from 105MB to 96MB
11-06 05:22:16.535 5826-5826/com.tomaszmarzeion.notepad I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 7% free, 89MB/96MB, paused 130us total 5.812ms
11-06 05:22:16.536 5826-5826/com.tomaszmarzeion.notepad E/art: Throwing OutOfMemoryError "Failed to allocate a 12879372 byte allocation with 7124636 free bytes and 6MB until OOM"
11-06 05:22:16.536 5826-5826/com.tomaszmarzeion.notepad D/skia: --- decoder->decode returned false
11-06 05:22:16.536 5826-5826/com.tomaszmarzeion.notepad D/AndroidRuntime: Shutting down VM
11-06 05:22:16.536 5826-5826/com.tomaszmarzeion.notepad E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.tomaszmarzeion.notepad, PID: 5826
                                                                          java.lang.OutOfMemoryError: Failed to allocate a 12879372 byte allocation with 7124636 free bytes and 6MB until OOM
                                                                              at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                              at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
                                                                              at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:522)
                                                                              at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:545)
                                                                              at com.example.tomek.notepad.BitmapConverter.getImage(BitmapConverter.java:26)
                                                                              at com.example.tomek.notepad.DatabaseHandler.getAllNotesAsArrayList(DatabaseHandler.java:211)
                                                                              at com.example.tomek.notepad.SaveOrUpdateNoteTask.onPostExecute(SaveOrUpdateNoteTask.java:45)
                                                                              at com.example.tomek.notepad.SaveOrUpdateNoteTask.onPostExecute(SaveOrUpdateNoteTask.java:9)
                                                                              at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                              at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                              at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
=================================================================
